#6/overflow in home and profile screen fixed
Photon3009/Auberge pull request #8
Opened 2024-01-15 03:40 UTC by YuvrajSingh3110

Issue #6 fixed with fixing the overflow in home screen and UI issue in profile screen

2024-01-15 06:06 UTC, Photon3009 commented on lib/view/nav_bar/home_screen.dart
> -                                  }
Avoid making changes for unnecessary indentation

2024-01-15 06:13 UTC, Photon3009 requested changes
I have tested your changes, and the homescreen is still getting overflowed by 13 pixels. This means that it is still device-specific. As for the profile screen, I recommend making adjustments so that we don't have to make the content scrollable. This can be achieved by adjusting the font size and padding using MediaQuery.
Try to update code as per the suggestions and I will convert this PR from easy to medium level. So, you still have 2 more days.

2024-01-16 11:06 UTC, YuvrajSingh3110 commented
please review the changes if the issue still persists or not

2024-01-17 09:05 UTC, Photon3009 approved these changes

2024-01-17 09:10 UTC, Photon3009 commented
@YuvrajSingh3110  Good work! I am merging this branch, but the profile screen is still device-specific. I recommend creating a new issue for that.

2024-01-17 09:10 UTC, merged